CREATE TABLE IF NOT EXISTS links (
 slug TEXT PRIMARY KEY NOT NULL,
 url TEXT NOT NULL,
 title TEXT NOT NULL DEFAULT '',
 active INTEGER NOT NULL DEFAULT 1,
 permanent INTEGER NOT NULL DEFAULT 0,
 clicks INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL,
 updated_at TEXT NOT NULL,
 last_click_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_links_created_at ON links(created_at DESC);
CREATE TABLE IF NOT EXISTS login_attempts (
 ip TEXT PRIMARY KEY NOT NULL,
 attempts INTEGER NOT NULL DEFAULT 0,
 expires_at INTEGER NOT NULL
);
